require('jquery')
require('./countryList.js')

$('.phone').cntr({inputCountryName: 'country1', inputPhoneName: 'phone1'})
$('.flags').cntr({flagInSelect: true, inputCountryName: 'country2', inputPhoneName: 'phone2'})
$('.flag').cntr({flagInInput: true, inputCountryName: 'country3', inputPhoneName: 'phone3'})
$('.select').cntr({select: true})
$('.search').cntr({search: true, inputCountryName: 'country4'})
$('.choose').cntr({select: true, list: true, countryAll: ['ar', 'fr']})
$('.delete').cntr({select: true, delete: true, countryAll: ['ar', 'ua']})
